<script lang="ts">
    import { page } from "$app/stores";

    import Layout from "$lib/components/layouts/layout.svelte";
    import Metadata from "$lib/components/layouts/metadata.svelte";

    let { children } = $props();
    const metadata = {
        title: "Blog ─ Yadhst",
        description:
            "A blog featuring unique insights, history, and in-depth exploration of diverse topics, from intriguing concepts to random thoughts, inviting readers to broaden their perspectives.",
        cover: "https://api.microlink.io/?url=https%3A%2F%2Fyadh-blog.vercel.app%2F&amp;screenshot=true&amp;meta=false&amp;waitForTimeout=8000&amp;embed=screenshot.url&amp;colorScheme=dark&amp;ttl=1d&amp;viewport.isMobile=true&amp;viewport.deviceScaleFactor=1&amp;viewport.width=1200&amp;viewport.height=630",
    };
</script>

<Metadata
    title={metadata.title}
    description={metadata.description}
    keywords={[
        "blog",
        "random thoughts",
        "intriguing concepts",
        "diverse topics",
    ]}
    author={{
        name: "Yadhst",
        url: "https://github.com/yadhst",
    }}
    openGraph={{
        title: metadata.title,
        description: metadata.description,
        url: $page.url.href,
        site_name: metadata.title,
        locale: "en_US",
        type: "website",
        image: {
            url: metadata.cover,
            width: 1200,
            height: 630,
            alt: "Website Preview Generated by microlink.io",
        },
    }}
    twitter={{
        card: "summary_large_image",
        title: metadata.title,
        description: metadata.description,
        site: "@yadhst",
        image: {
            url: metadata.cover,
            width: 1200,
            height: 630,
            alt: "Website Preview Generated by microlink.io",
        },
    }}
/>

<Layout>
    <div class="mt-6 flex-1">
        {@render children()}
    </div>
</Layout>
